### ISSUE TITLE
-hostname=10.32.0.1 , where to get this value

### ISSUE THREAD

**Issue by prabhatpankaj** [ivanfioravanti/kubernetes-the-hard-way-on-azure#14]
https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/edit/master/docs/04-certificate-authority.md#L249

Can you please tell me what is this ip address ?

-hostname=10.32.0.1

**Comment by codependent** [comment]
Here you have a very clear explanation, hope it helps: https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/issues/14

**Comment by ivanfioravanti** [comment]
Thanks @codependent
