### ISSUE TITLE
Walk failed: GetFileAttributesEx version: The system cannot find the file specified.

### ISSUE THREAD

**Issue by Pandeysiddharth** [ivanfioravanti/kubernetes-the-hard-way-on-azure#15]
I am getting the below error when I try to install CFSSLJSON:

PS C:\windows\system32> Invoke-WebRequest -Uri https://pkg.cfssl.org/R1.2/mkbundle_windows-amd64.exe -OutFile cfssljson.exe
PS C:\windows\system32> cfssljson version
<Date> <Time> [INFO] Found version
<Date> <Time> [ERROR] Walk failed: GetFileAttributesEx version: The system cannot find the file specified.
<Date> <Time> [INFO] Wrote 0 certificates.

Error persists even after downloading and running file from the browser link instead of running it in powershell.

**Comment by ivanfioravanti** [comment]
Is this still happening?
