### ISSUE TITLE
Why Ubuntu Server 16.04 instead Moby Linux?

### ISSUE THREAD

**Issue by alexsandro-xpt** [ivanfioravanti/kubernetes-the-hard-way-on-azure#17]
I'm looking for dedicated Linux for containers proposes. And I guess Moby Linux is the right. Why not setup with this distribution?

**Comment by ivanfioravanti** [comment]
Just to keep it consistent with the original guide created by Kelsey Hightower [here](https://github.com/kelseyhightower/kubernetes-the-hard-way).
