### ISSUE TITLE
DNS Cluster Add-on issue

### ISSUE THREAD

**Issue by CptQuint** [ivanfioravanti/kubernetes-the-hard-way-on-azure#19]
All seems fine with the exception of the DNS add-on, despite all appearing well kube-dns fails to resolve anything:

```
PS C:\Users\user> kubectl get service --all-namespaces
NAMESPACE     NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
default       kubernetes   ClusterIP   10.32.0.1    <none>        443/TCP         6d
kube-system   kube-dns     ClusterIP   10.32.0.10   <none>        53/UDP,53/TCP   2h

PS C:\Users\user> kubectl exec -ti $POD_NAME -- nslookup kubernetes.default
Server:         10.32.0.10
Address:        10.32.0.10:53

** server can't find kubernetes.default: NXDOMAIN

*** Can't find kubernetes.default: No answer

PS C:\Users\user> kubectl exec -ti $POD_NAME -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local iuupro2pvonutmgl325yqnbsdsh.fx.internal.cloudapp.net
nameserver 10.32.0.10
options ndots:5

**Comment by CptQuint** [comment]
Just in case anybody else is experiencing the same issue and pulling their hair out.

It looks like DNS inside the latest busybox release isn't working properly. It works for me with busybox images <= 1.28.4.

**Comment by ITTaskForce** [comment]
yep, i can confirm that using busybox image from the kubernetes dns troubleshooting doc works, where as this guide busybox image doesnt work.

**Comment by 4c74356b41** [comment]
https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/pull/24 fix for this

**Comment by 4c74356b41** [comment]
this can be closed @ivanfioravanti
