### ISSUE TITLE
Prerequisite - SSH keys are required (e.g. during VM provisioning)

### ISSUE THREAD

**Issue by DenisBiondic** [ivanfioravanti/kubernetes-the-hard-way-on-azure#3]
VMs fail if there is no SSH key available (in .ssh directory). For example. on Linux these can be created using "ssh-keygen -t rsa". It might be a good step in prerequisites section?

**Comment by DenisBiondic** [comment]
Also raised the issue here: https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/238

**Comment by ivanfioravanti** [comment]
Good idea, we can add it, but the best would be adding it to main Repo from Kelsey

**Comment by jboeshart** [comment]
Any chance we could add this in to these docs? I don't see any movement on the linked issue in the main repo. Happy to log a PR on this one with the updates if that's cool.

**Comment by pmanlukas** [comment]
Any workaround so far?

**Comment by lucifer** [comment]
If your working through this on a vanila machine, VM whatever; you could give `apt-get install ssh` a try. Not an in-depth work around but mostly enough. If gcloud sees SSH installed it usually offers mitigating options in the absence of keys.

**Comment by cloudmelon** [comment]
I believe the issue can be resolved by adding '  --generate-ssh-keys ' as parameter ( here is an example of cmdlet should use : )

for i in 0 1 2; do
    echo "[Controller ${i}] Creating public IP..."
    az network public-ip create -n controller-${i}-pip -g kubernetes > /dev/null

    echo "[Controller ${i}] Creating NIC..."
    az network nic create -g kubernetes \
        -n controller-${i}-nic \
        --private-ip-address 10.240.0.1${i} \
        --public-ip-address controller-${i}-pip \
        --vnet kubernetes-vnet \
        --subnet kubernetes-subnet \
        --ip-forwarding \
        --lb-name kubernetes-lb \
        --lb-address-pools kubernetes-lb-pool > /dev/null

    echo "[Controller ${i}] Creating VM..."
    az vm create -g kubernetes \
        -n controller-${i} \
        --image ${UBUNTULTS} \
        --generate-ssh-keys \
        --nics controller-${i}-nic \
        --availability-set controller-as \
        --nsg '' \
        --admin-username 'kuberoot' > /dev/null \
        --generate-ssh-keys
done

![image](https://user-images.githubusercontent.com/4621560/57770693-c3353a80-7708-11e9-9f44-68ca7e0279c6.png)


Pull request will be created for this. More than happy to help more on this.

**Comment by ivanfioravanti** [comment]
Merged. Thanks!
