### ISSUE TITLE
cfssljson version not defined

### ISSUE THREAD

**Issue by cloudmelon** [ivanfioravanti/kubernetes-the-hard-way-on-azure#37]
The issue is cause by cfssljson version parameter not defined.

In the repo says 
cfssljson -version which is not correct ( as follows )

![image](https://user-images.githubusercontent.com/4621560/57769529-0a6dfc00-7706-11e9-9137-28dd85883b42.png)

I believe the correct practice is to provide version and help as parameter so that we can use the following 

cfssljson version
cfssljson help 

Thanks

**Comment by ivanfioravanti** [comment]
Thanks for the Pull Request on this one.
