### ISSUE TITLE
Kubectl unable to connect on masters

### ISSUE THREAD

**Issue by timothydlister** [ivanfioravanti/kubernetes-the-hard-way-on-azure#39]
Hello,

Apologies if this is not the correct place to ask this. I have been following these instructions on Azure using the free tier with demo license.

First off contrary to the instructions, I am only able to create four VMs. In my case I have settled with 2 controllers and 2 workers.

While following along **08-bootstrapping-kubernetes-controllers.md** and attempting to verify everything works, I am unable to connect to the apiserver locally from the master.

`kuberoot@controller-0:~$ kubectl get componentstatuses --kubeconfig admin.kubeconfig
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?`

If anyone can provide feedback of a point in the right direction, it would be much appreciated.

Thank you kindly,

`kuberoot@controller-0:~$ kubectl config view --kubeconfig admin.kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:6443
  name: kubernetes-the-hard-way
contexts:
- context:
    cluster: kubernetes-the-hard-way
    user: admin
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED`

Output of **journalctl -u kube-apiserver** is here:
https://pastebin.com/zgxkAtj3

**Comment by ivanfioravanti** [comment]
Hi Timothy,
In prerequisites it’s defined that with Free Trial you have limited number of cores and you have to create 4 VMs only.
https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/blob/master/docs/01-prerequisites.md#microsoft-azure

For the issue, I’ll try to reproduce it on my side and cime back to you soon.

**Comment by timothydlister** [comment]
Ah Thanks Ivan!

Apologies that I missed that bit.

I appreciate any help you can offer.

Cheers,

**Comment by timothydlister** [comment]
Hey Ivan,

Go ahead and close this. It ended up being a fluke on my side with the etcd cluster. Either I wasn't waiting long enough or didn't follow the directions correctly.

Kind regards.
