### ISSUE TITLE
Issue when running 

### ISSUE THREAD

**Issue by shubhammicrosoft1** [ivanfioravanti/kubernetes-the-hard-way-on-azure#64]
I am using Azure VM to bootstrap the cluster using below commands
sudo ETCDCTL_API=3 etcdctl member list \
  --endpoints=https://${INTERNAL_IP}:2379 \
  --cacert=/etc/etcd/ca.pem \
  --cert=/etc/etcd/kubernetes.pem \
  --key=/etc/etcd/kubernetes-key.pem

However it is failing with below error -
"retrying of unary invoker failed" probably due to "Connection timeout" issue

I tried increasing the size of VM (as suggested in one of Github articles) but the issue still persists , any help or guidance you can extend for the same

**Comment by ivanfioravanti** [comment]
Can you please retry with latest push? It should work. I'll close the issue for now, quite old, sorry for the delay
