### ISSUE TITLE
etcdctl: command not found

### ISSUE THREAD

**Issue by AErmie** [ivanfioravanti/kubernetes-the-hard-way-on-azure#65]
When following the instructions for [Bootstrapping the etcd Cluster](https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/blob/master/docs/07-bootstrapping-etcd.md), you are instructed to run a specific command to list the etcd cluster members. 

```bash
sudo ETCDCTL_API=3 etcdctl member list \
  --endpoints=https://${INTERNAL_IP}:2379 \
  --cacert=/etc/etcd/ca.pem \
  --cert=/etc/etcd/kubernetes.pem \
  --key=/etc/etcd/kubernetes-key.pem
```

However, when you do so, you encounter the error: 
`sudo: etcdctl: command not found`

The reason is because etcdctl is not already installed. You should add to the [Installing the Client Tools](https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/blob/master/docs/02-client-tools.md) instructions, to also install etcdctl, via the `sudo apt install etcd-client` command.

**Comment by ivanfioravanti** [comment]
No need for this, it's part of 
[Download and Install the etcd Binaries](https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/blob/master/docs/07-bootstrapping-etcd.md#download-and-install-the-etcd-binaries)
