### ISSUE TITLE
unable to start etcd

### ISSUE THREAD

**Issue by devopslearn15** [ivanfioravanti/kubernetes-the-hard-way-on-azure#71]
Please help me fix the below error, i am facing this when i try to start the etcd.

kuberoot@controller-0:~$ {
>   sudo systemctl daemon-reload
>   sudo systemctl enable etcd
>   sudo systemctl start etcd
> }
Created symlink /etc/systemd/system/multi-user.target.wants/etcd.service → /etc/systemd/system/etcd.service.
Job for etcd.service failed because a timeout was exceeded.
See "systemctl status etcd.service" and "journalctl -xe" for details.
kuberoot@controller-0:~$ journalctl -xe
Jan 15 14:06:37 controller-0 etcd[3392]: health check for peer ffed16798470cab5 could not connect: dial tcp 10.240.0.11:2380: connect: connection refused (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Jan 15 14:06:37 controller-0 etcd[3392]: health check for peer 3a57933972cb5131 could not connect: dial tcp 10.240.0.12:2380: connect: connection refused (prober "ROUND_TRIPPER_SNAPSHOT")
Jan 15 14:06:37 controller-0 etcd[3392]: health check for peer ffed16798470cab5 could not connect: dial tcp 10.240.0.11:2380: connect: connection refused (prober "ROUND_TRIPPER_SNAPSHOT")
Jan 15 14:06:38 controller-0 etcd[3392]: f98dc20bce6225a0 is starting a new election at term 148
Jan 15 14:06:38 controller-0 etcd[3392]: f98dc20bce6225a0 became candidate at term 149
Jan 15 14:06:38 controller-0 etcd[3392]: f98dc20bce6225a0 received MsgVoteResp from f98dc20bce6225a0 at term 149
Jan 15 14:06:38 controller-0 etcd[3392]: f98dc20bce6225a0 [logterm: 1, index: 3] sent MsgVote request to ffed16798470cab5 at term 149
Jan 15 14:06:38 controller-0 etcd[3392]: f98dc20bce6225a0 [logterm: 1, index: 3] sent MsgVote request to 3a57933972cb5131 at term 149
Jan 15 14:06:39 controller-0 sshd[3434]: Invalid user baikal from 207.118.182.172 port 34502
Jan 15 14:06:39 controller-0 sshd[3434]: Received disconnect from 207.118.182.172 port 34502:11: disconnected by user [preauth]
Jan 15 14:06:39 controller-0 sshd[3434]: Disconnected from invalid user baikal 207.118.182.172 port 34502 [preauth]
Jan 15 14:06:39 controller-0 etcd[3392]: f98dc20bce6225a0 is starting a new election at term 149
Jan 15 14:06:39 controller-0 etcd[3392]: f98dc20bce6225a0 became candidate at term 150

**Comment by kinkaraCoding** [comment]
I had quite the some problem and could solve it by installing all steps for controller-1 and controller-2 before controller-0. I not sure why but i helps in my case.

**Comment by ivanfioravanti** [comment]
Yes, all controllers must be configured to be able to see this works
