### ISSUE TITLE
kubectl and kube-proxy unable to connect to load balancer in 09-bootstrapping-kubernetes-workers

### ISSUE THREAD

**Issue by PierreAdrienPonthieu** [ivanfioravanti/kubernetes-the-hard-way-on-azure#77]
When executing `kubectl get nodes` no ressources were found.
After investigation of logs using `journalctl -fu kube-proxy` and `journalctl -fu kube-proxy` it turned out it was due to the missing IP of the load balancer (processes were trying to make connection to https://:6443 instead of http://${LOAD_BALANCER_IP}:6443).
I had to modify the address in the server section of `/var/lib/kubelet/kubeconfig` and `/var/lib/kube-proxy/kubeconfig`

**Comment by ivanfioravanti** [comment]
It's working now after last update
